service_name: travis-ci

src_dir: engine/Shopware/Plugins/Community/Core/SatagMd5Osc/

coverage_clover: engine/Shopware/Plugins/Community/Core/SatagMd5Osc/build/logs/clover.xml
json_path: engine/Shopware/Plugins/Community/Core/SatagMd5Osc/build/logs/coveralls-upload.json