sudo: false

language: php

php:
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

addons:
  apt:
    packages:
    - default-jdk
    - ant

before_install:
  - mysql -e "create database IF NOT EXISTS shopware;" -uroot

install:
  # Get Shopware
  - git clone https://github.com/shopware/shopware.git ./shopware
  - cp ./travis/build.properties ./shopware/build/
  - cd ./shopware/build
  - ant build-unit
  - cd ./../..
  - cp -r ./Core ./shopware/engine/Shopware/Plugins/Community

before_script:
  - cd ./shopware/engine/Shopware/Plugins/Community/Core/SatagMd5Osc

script: phpunit