sudo: false

language: php

php:
  - 5.5
  - 5.6
  - hhvm

cache:
   directories:
     - $HOME/.composer/cache

matrix:
  allow_failures:
    - php: hhvm

addons:
  apt:
    packages:
    - default-jdk
    - ant

before_install:
  - mysql -e "create database IF NOT EXISTS shopware;" -uroot

install:
  # Get Shopware
  - git clone https://github.com/shopware/shopware.git ./shopware
  - cp ./travis/build.properties ./shopware/build/
  - cd ./shopware/build
  - ant build-unit
  - cd ./../..
  - cp -r ./Core ./shopware/engine/Shopware/Plugins/Community
  # add coveralls support
  - composer require --dev "satooshi/php-coveralls:dev-master"

before_script:
  - cd ./engine/Shopware/Plugins/Community/Core/SatagMd5Osc

script: phpunit --coverage-clover build/logs/clover.xml

after_script: php ./../../../../../../vendor/bin/coveralls -v